name: On PR
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  verify-codebase:
    permissions:
      contents: write
    name: "Verify codebase"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v3
      - name: "Setup NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Setup JDK"
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
      - name: Install Dependencies
        run: npm install
      - name: Compile TypeScript
        run: npm run compile
      - name: Lint
        run: npm run lint
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v36
        with:
          separator: ","
          files: |
            packages/testsuite/cypress/e2e/**/*.cy.ts
      - name: "Run tests of modified files"
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          cd packages/testsuite
          SPECS=$(echo ${{ steps.changed-files-specific.outputs.all_changed_files }} | sed "s|packages/testsuite/||g")
          npm run test-compiled -- --browser=chrome --specs=$SPECS
