name: "Reusable Build Project Workflow"
on:
  workflow_call:
    inputs:
      spec:
        type: string
        required: false
        description: "Comma delimited test spec file(s) to run."
jobs:
  build_project_job:
    name: "Build Project"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v4
      - name: "Setup NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: "Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "17"
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: "latest-esr"
      - name: "Run npm install"
        run: "npm install"
      - name: "Run compile"
        run: "npm run compile"
      - name: "Run all tests"
        if: "${{ github.event.inputs.spec == '' }}"
        run: "npm run test:compiled"
      - name: "Run specific test"
        if: "${{ github.event.inputs.spec != '' }}"
        run: "npm run test:compiled -- --specs=${{ inputs.spec }}"
